config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  get '/recipes/public'
  resources :foods, only: [:index, :new, :create, :destroy, :show]
  resources :recipes, except: [:edit, :update] do
    member do
      patch :public_toggle
    end
  end
  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, except: %i[edit update]
    collection do
      get 'public'
    end
    member do
      get 'general_shopping_list'
    end
  end
  resources :recipe_foods, only: [:new, :create, :destroy] do
    patch :modify, on: :member
  end
  root "welcome#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # Associations
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood'
  has_and_belongs_to_many :foods, join_table: 'recipe_foods'
  # Attributes
  attribute :name, :string
  attribute :preparation_time_minutes, :integer
  attribute :cooking_time_minutes, :integer
  attribute :description, :string
  attribute :is_public, :boolean

  # Callbacks

  # Validations
  validates :is_public, inclusion: { in: [true, false] }
  validates :name, :preparation_time_minutes, :cooking_time_minutes, presence: true
  validates :preparation_time_minutes, :cooking_time_minutes, numericality: { only_integer: true }
  # Mehtods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'The recipe was succesfuly created'
    else
      render :new, alert: 'The recipe was not created'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipe_path, notice: 'The recipe was deleted'
  end

  def public
    @recipes = Recipe.where(is_public: true).order(created_at: :desc)
    render 'public'
  end

  def public_toggle
    @recipe = Recipe.find(params[:id])
    @recipe.is_public = !@recipe.is_public
    @recipe.save
    redirect_to recipe_path(@recipe), notice: "The recipe is now #{@recipe.is_public ? 'public' : 'private'}"
  end

  def general_shopping_list
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find_by(id: params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    @needed_items = []
    @recipe_foods.each do |recipe_food|
      existed_food = @user.foods.find_by(name: recipe_food.food.name)
      if existed_food.nil?
        @needed_items << [recipe_food.food.name, recipe_food.quantity, recipe_food.food.price,
                          recipe_food.food.measurement_unit]
      else
        difference_quantity = recipe_food.quantity - existed_food.quantity
        if difference_quantity.positive?
          @needed_items << [recipe_food.food.name, difference_quantity, existed_food.price,
                            existed_food.measurement_unit]
        end
      end
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time_minutes, :cooking_time_minutes, :description, :is_public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<div class="recipe">
<%= link_to "Add new recipe", new_recipe_path, class: "add btn btn-dark" %>
  <h3 class="food_title">Here is a list of my recipes:</h3>
  <% recipes.each do |recipe|%>
    <div class='recipe_box table'>
      <div class='recipe_name '>
      <h3 class=""><%= link_to "#{recipe.name}", recipe_path(recipe.id) %></h3>
      <span class="btn"><%= link_to "REMOVE", recipe_path(recipe), data: { turbo_method: :delete, confirm: 'Are you sure?' } %></span>
      </div>
        <p><%= recipe.description%></p>
    </div>
  <%end%>
</div>

app/views/recipes/general_shopping_list.html.erb
<h3>Shopping list</h3>
<div class="amount">
  <p>Amount of food to buy: <%= @needed_items.length %></p>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <% @needed_items.each do |needed_item| %>
    <tbody>
      <tr>
        <td><%= needed_item[0] %></td>
        <td><%= needed_item[1]  %><%= needed_item[3] %></td>
        <td><%= needed_item[1] * needed_item[2] %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/recipes/index.html.erb
<%= render partial: 'recipe', locals: {recipes: @recipes} %>

app/views/recipes/new.html.erb
<h4>Add new food recipe</h4>

<%= form_for @recipe, url: recipes_path do |form| %>
  <div class="input noBorder">
    <%= form.text_field :name, placeholder: "Recipe title...", required: true%>
  </div>
  <div class="input noBorder">
    <%= form.text_field :description, placeholder: "Recipe description...", required: true%>
  </div>
    <div class="input noBorder">
    <%= form.text_field :preparation_time_minutes, placeholder: "Preparation time in minutes", required: true%>
  </div>
  <div class="input noBorder">
    <%= form.text_field :cooking_time_minutes, placeholder: "Cooking time in minutes", required: true%>
  </div>  
  <div class="input noBorder">
    <%= form.select :is_public, options_for_select(['true', 'false']), prompt: 'Publuc or private?' %>
  </div>
 <button class="btn btn-dark">
  <%= form.submit "Create Recipe", class: "btn btn-dark noBorder" %>
</button>
 <%end%>

app/views/recipes/public.html.erb
<div class="public">
  <h3>Here is a list of public recipes</h3>
  <% @recipes.each do |recipe| %>
    <div class='recipe_box'>
      <div class='recipe_name'>
        <%= link_to "#{recipe.name}", recipe_path(recipe.id) %>
        <p>by: <%= recipe.user.name %></p>
      </div>
      <div class='detail'>
        <p>total number of foods: <%= recipe.foods.count %></p>
        <p>total price of foods: $<%= recipe.foods.sum(:price) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h3>Recipe no.<%= @recipe.id %> full description</h3>
<h3><%= @recipe.name %></h3>
<section class="recipe-details">
  <div class="d-flex gap">
    <div class="right">
      <p class="input">Preparation time: <%= @recipe.preparation_time_minutes %> mins </p>
      <p  class="input">Cooking time: <%= @recipe.cooking_time_minutes %> mins </p>
    </div>
    <%= form_for @recipe, url: public_toggle_recipe_path(@recipe), method: :patch, remote: true, authenticity_token: true, html: { class: 'toggle-form' } do |f| %>
        <div class="slider-container">
        <span class="switch-label">Public</span>
        <label class="switch">
          <%= f.check_box :is_public, { class: "toggle-switch" }, 0, 1 %>
          <span class="slider round"></span>
        </label>
      </div>
      <%= f.hidden_field :is_public, value: @recipe.is_public ? 0 : 1 %>
      <%= f.submit 'Toggle', class: 'hidden-submit', style: 'display: none;' %>
    <% end %>
  </div>
  <p  class="input"><%= @recipe.description%></p>
  <div class="d-flex gap bottom-line p-1">
    <%= link_to  "Generate shopping list", general_shopping_list_recipe_path(@recipe), method: :post, class: "btn btn-dark" %>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-dark" %>
  </div>
</section>
 <%if @recipe_foods == []%>
      <h2>you have no food ingredients yet, click on "Add ingredient" to add to the list</h2>
    <%else%>
<table class="table">
  <thead>
    <tr>
      <th class="input title">Food</th>
      <th class="input title">Quantity</th>
      <th class="input title">Value</th>
      <th class="input title">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td class="input"><%= recipe_food.food.name %></td>
        <td class="input"><%= recipe_food.quantity %></td>
        <td class="input"><%= recipe_food.food.price %></td>
        <td class="input">
          <%= link_to 'Delete', recipe_food_path(recipe_food), data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: 'btn btn-dark' %>
          <button class="modify-button btn btn-dark">Modify</button>
          <div class="modify-form" style="display: none;">
            <%= form_for recipe_food, url: modify_recipe_food_path(recipe_food), method: :patch, remote: true, authenticity_token: true do |f| %>
              <%= f.label :quantity %>
              <%= f.text_field :quantity, value: recipe_food.quantity %>
              <%= f.submit 'Update', class: 'modify-submit' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
    <%end%>
</table>

<%= javascript_include_tag "recipe", "data-turbolinks-track" => true  %>