config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  get '/recipes/public'
  resources :foods, only: [:index, :new, :create, :destroy, :show]
  resources :recipes, except: [:edit, :update] do
    member do
      patch :public_toggle
    end
  end
  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, except: %i[edit update]
    collection do
      get 'public'
    end
    member do
      get 'general_shopping_list'
    end
  end
  resources :recipe_foods, only: [:new, :create, :destroy] do
    patch :modify, on: :member
  end
  root "welcome#index"
end

app/views/home/_header.html.erb
<ul class="nav nav-underline navbar-dark bg-dark">
<%= link_to 'Recipe App', root_path, class:"navbar-brand" %>
   <% if user_signed_in? %>
  <li class="nav-item">
  <%= link_to 'Sign Out', destroy_user_session_path, class:"nav-link", data: { turbo_method: :delete } %>
  </li>
  <%# public recipes %>
  <li class="nav-item">
    <%= link_to "Public Recipes", public_recipes_path, method: :get, class:"nav-link" %>
  </li>
  <%# my recipes %>
  <li class="nav-item">
    <%= link_to "My Recipes", recipes_path, method: :delete, class:"nav-link" %>
  </li>
  <%# add recipe %>
   <li class="nav-item">
      <%= link_to "New Recipe", new_recipe_path, method: :delete, class:"nav-link" %>
    </li>
  <%# foods %>
  <li class="nav-item">
    <%= link_to "Food", foods_path, class:"nav-link" %>
  </li>
  <%# add foods %>
   <li class="nav-item">
       <%= link_to "Add Food", new_food_path, class:"nav-link" %>
  </li>
  <%# shopping list %>
    <li class="nav-item">
       <%#= link_to "Shopping list", general_shopping_list_recipe_path, class:"nav-link" %>
  </li>
    <% else %>
  <li class="nav-item">
    <%= link_to "Sign Up/In", new_user_session_path, class:"nav-link" %>
  </li>
  <% end %>
  
</ul>