config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  get '/recipes/public'
  resources :foods, only: [:index, :new, :create, :destroy, :show]
  resources :recipes, except: [:edit, :update] do
    member do
      patch :public_toggle
    end
  end
  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, except: %i[edit update]
    collection do
      get 'public'
    end
    member do
      get 'general_shopping_list'
    end
  end
  resources :recipe_foods, only: [:new, :create, :destroy] do
    patch :modify, on: :member
  end
  root "welcome#index"
end

app/models/food.rb
class Food < ApplicationRecord
  # Associations
  belongs_to :user, class_name: 'User', optional: true
  has_many :recipe_foods, class_name: 'RecipeFood'
  has_and_belongs_to_many :recipes, join_table: 'recipe_foods'

  # Attributes
  attribute :name, :string
  attribute :measurement_unit, :string
  attribute :price, :decimal
  attribute :quantity, :integer

  # Callbacks

  # Validations
  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
  # Mehtods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(post_food)
    @food.user = current_user
    if @food.save
      flash[:success] = 'Food was successfully added.'
      redirect_to foods_path, notice: 'Food was successfully added.'
    else
      flash[:error] = 'Food does not exist in your food list, please add it to your food list.'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food.'
    end
    redirect_to foods_path, notice: 'Food was successfully deleted.'
  end

  def post_food
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<%= link_to "Add Food", new_food_path, method: :post, class: "btn btn-dark add" %>
<h3 class="food_title">Foods page</h3>
<table class="table">
  <thead>
    <tr>
      <th class="input title" >Food</th>
      <th class="input title" >Measurement unit</th>
      <th class="input title">Unit price</th>
      <th class="input title">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class="input"><%= food.name %></td>
        <td class="input"><%= food.measurement_unit %></td>
        <td class="input"><%= food.price %></td>
        <td class="input">
            <%= link_to 'Delete', food_path(food), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<div class="form ff">
<h4> Add new food</h4>

<%= form_with model: @food, url: foods_path do |form| %>
  <div class="input noBorder">
    <%= form.text_field :name, placeholder: "Name of the food...", required: true%>
  </div>
  <div class="input noBorder">
        <%= form.select :measurement_unit, options_for_select(['units', 'grams', 'kg', 'pounds']), { prompt: 'Select a category  ...' }, class: 'form-select my-2 btn btn-outline-secondary', style: 'height:40px; width:235px' %>
  </div>
  <div class="input noBorder">
    <%= form.number_field :price, placeholder: "Enter food price...", required: true%>
  </div>
  <div class="input noBorder">
    <%= form.number_field :quantity, placeholder: "Enter quantity value...", required: true%>
  </div>
  <%=form.submit "Create food", class: "submit btn btn-dark"%>
<%end%>
</div>