config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  get '/recipes/public'
  resources :foods, only: [:index, :new, :create, :destroy, :show]
  resources :recipes, except: [:edit, :update] do
    member do
      patch :public_toggle
    end
  end
  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, except: %i[edit update]
    collection do
      get 'public'
    end
    member do
      get 'general_shopping_list'
    end
  end
  resources :recipe_foods, only: [:new, :create, :destroy] do
    patch :modify, on: :member
  end
  root "welcome#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  # Associations
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  # Attributes
  attribute :quantity, :integer

  # Callbacks

  # Validations
  validates :quantity, presence: true

  # Mehtods
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def show
    recipe_food = RecipeFood.find(params[:id])
    redirect_to recipe_path(recipe_food.recipe)
  end

  def new
    @user = current_user
    @foods = @user.foods
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @ingredients = []
    @foods.each do |food|
      @ingredients << ("#{food.name} in #{food.measurement_unit}")
    end
  end

  def create
    recipe = Recipe.find(params[:recipe_id])
    quantity = params[:recipe_food][:quantity]
    food_unit = params[:recipe_food][:food]
    food_name = food_unit.split.first
    food = Food.find_by(name: food_name)

    recipe_food = RecipeFood.new(food:, recipe:, quantity:)
    puts food.id
    if recipe_food.save
      flash[:success] = 'Object successfully created'
      redirect_to recipe_path(recipe)
    else
      flash[:error] = 'Failed to create the recipe food'
      render 'new'
    end
  end

  def modify
    recipe_food = RecipeFood.find(params[:id])
    new_quantity = params[:recipe_food][:quantity]

    if recipe_food.update(quantity: new_quantity)
      flash[:success] = 'Quantity updated successfully'
    else
      flash[:error] = 'Failed to update quantity'
    end

    redirect_to recipe_food_path(recipe_food)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food.'
    end
    redirect_to recipes_path, notice: 'Food was successfully deleted.'
  end
end

app/views/recipe_foods/new.html.erb
<div class="form ff">
  <h4>Add new Ingredient</h4>
  <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), local: true) do |form| %>
    <div class="input noBorder">
<%= form.select :food, options_for_select(@ingredients), { prompt: 'Pick ingredient...' }, class: 'form-select my-2 btn btn-outline-secondary', style: 'height:40px; width:250px' %>
        <%= link_to "Add Food", new_food_path, class: "btn btn-dark", method: :post %>
    </div>
    <div class="input noBorder">
      <%= form.text_field :quantity, placeholder: 'Enter quantity', required: true, class: 'form-input' %>
    </div>

    <%= form.submit "Create Ingredient", class: "submit btn btn-dark" %>
  <% end %>
</div>